### ISSUE TITLE
Unable to open Matlab models

### ISSUE THREAD

**Issue by Midnighter** [EPFL-LCSB/pytfa#2]
I tried to run the tutorials and with each one of them I get the same `ValueError` when the scripts try to read the models. As an example, `python tutorial_basics.py` causes the following traceback:

```python
Traceback (most recent call last):
  File "tutorial_basics.py", line 18, in <module>
    cobra_model = import_matlab_model('../models/small_ecoli.mat')
  File ".virtualenvs/tfa/lib/python3.6/site-packages/pytfa/io/base.py", line 39, in import_matlab_model
    mat_data = loadmat(path)
  File ".virtualenvs/tfa/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File ".virtualenvs/tfa/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 59, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File ".virtualenvs/tfa/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 50, 56
```

I'm using Python 3.6, `cobra==0.11.2` , and `scipy==0.19.0`. I get exactly the same error with `scipy==1.0.0`, though.

Two comments:

1. There is a function in cobrapy `cobra.io.load_matlab_model` which may or may not be the same as `pytfa.io.import_matlab_model`. Internally they use the same scipy function. So same error.
2. I would have thought that, inside Matlab, you can export models to SBML by now. SBML is _the_ universal exchange format for models and distributing Matlab models with a Python package doesn't make a lot of sense to me.

**Comment by psalvy** [comment]
Hi,
My gut feeling is that your `git-lfs` is not properly initialized. You can check the `.mat` files in a text editor, and most probably they will look like:
```
version https://git-lfs.github.com/spec/v1
oid sha256:<a hash>
size <a number>
```
you can fix this with
```
git lfs install
git lfs pull
```
while inside the repo.
Also, from the look of your traceback, you do not use the docker provided with pytfa. If the previous changes do not fix your issue, perhaps you could try running it on the Docker? That would help tracking if it's a package issue or a local issue.

**Comment by Midnighter** [comment]
> My gut feeling is that your git-lfs is not properly initialized.

Indeed, that was the problem. Could you make a note of those two commands in the README, please? I saw that the repo requires git-lfs but since I do actually have it installed I simply skipped over that.

I tried building the Dockerfile but contrary to the description CPLEX is actually required and not optional.

And I still strongly encourage distributing models as SBML.

**Comment by ElderMedic** [comment]
Hey I have tried build and run the docker container with cplex and gurobi, I have everything in place (python3.6, gurobi 9.0.1 and cplex 12.8) as instructed and build&run seems good. But when I run the pytest in /src/pytfa, I still get the same error here:

```sh
(Fri Sep-9 4:13:27pm)-(CPU 8.5%:0:Net 1)-(pytfa:/src/pytfa)-(112K:21)
> pytest
===================================================== test session starts =====================================================
platform linux -- Python 3.6.15, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /src/pytfa
collected 4 items / 5 errors                                                                                                  

=========================================================== ERRORS ============================================================
___________________________________________ ERROR collecting tests/test_analysis.py ___________________________________________
tests/test_analysis.py:3: in <module>
    from settings import cobra_model, tmodel
tests/settings.py:39: in <module>
    + '/../models/small_ecoli.mat')
pytfa/io/base.py:43: in import_matlab_model
    mat_data = loadmat(path)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:223: in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:72: in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/miobase.py:231: in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
E   ValueError: Unknown mat file type, version 50, 56
------------------------------------------------------- Captured stderr -------------------------------------------------------
GUROBI is available but could not load with error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/optlang/gurobi_interface.py", line 40, in <module>
      raise RuntimeError()
  RuntimeError
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/optlang/__init__.py", line 49, in <module>
      from optlang import gurobi_interface
    File "/usr/local/lib/python3.6/site-packages/optlang/gurobi_interface.py", line 43, in <module>
      "This version of optlang requires a Gurobi version of 9.5 or above.")
  RuntimeError: This version of optlang requires a Gurobi version of 9.5 or above.
_____________________________________________ ERROR collecting tests/test_core.py _____________________________________________
tests/test_core.py:21: in <module>
    from settings import tmodel, this_directory, objective_value
tests/settings.py:39: in <module>
    + '/../models/small_ecoli.mat')
pytfa/io/base.py:43: in import_matlab_model
    mat_data = loadmat(path)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:223: in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:72: in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/miobase.py:231: in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
E   ValueError: Unknown mat file type, version 50, 56
______________________________________________ ERROR collecting tests/test_io.py ______________________________________________
tests/test_io.py:15: in <module>
    from settings import small_model, small_tmodel
tests/settings.py:39: in <module>
    + '/../models/small_ecoli.mat')
pytfa/io/base.py:43: in import_matlab_model
    mat_data = loadmat(path)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:223: in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:72: in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/miobase.py:231: in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
E   ValueError: Unknown mat file type, version 50, 56
____________________________________________ ERROR collecting tests/test_optim.py _____________________________________________
tests/test_optim.py:19: in <module>
    from settings import tmodel
tests/settings.py:39: in <module>
    + '/../models/small_ecoli.mat')
pytfa/io/base.py:43: in import_matlab_model
    mat_data = loadmat(path)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:223: in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:72: in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/miobase.py:231: in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
E   ValueError: Unknown mat file type, version 50, 56
____________________________________________ ERROR collecting tests/test_redgem.py ____________________________________________
tests/test_redgem.py:7: in <module>
    from settings import this_directory
tests/settings.py:39: in <module>
    + '/../models/small_ecoli.mat')
pytfa/io/base.py:43: in import_matlab_model
    mat_data = loadmat(path)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:223: in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/mio.py:72: in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
/usr/local/lib/python3.6/site-packages/scipy/io/matlab/miobase.py:231: in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
E   ValueError: Unknown mat file type, version 50, 56
====================================================== warnings summary =======================================================
/usr/local/lib/python3.6/site-packages/cplex/_internal/_pycplex.py:15
  /usr/local/lib/python3.6/site-packages/cplex/_internal/_pycplex.py:15 DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

pytfa/optim/variables.py:539
  /src/pytfa/pytfa/optim/variables.py:539 DeprecationWarning: invalid escape sequence \G

tests/test_equilibrator.py:31
  /src/pytfa/tests/test_equilibrator.py:31 PytestUnknownMarkWarning: Unknown pytest.mark.dependency - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html

tests/test_equilibrator.py:41
  /src/pytfa/tests/test_equilibrator.py:41 PytestUnknownMarkWarning: Unknown pytest.mark.dependency - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html

tests/test_equilibrator.py:51
  /src/pytfa/tests/test_equilibrator.py:51 PytestUnknownMarkWarning: Unknown pytest.mark.dependency - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================== short test summary info ===================================================
ERROR tests/test_analysis.py - ValueError: Unknown mat file type, version 50, 56
ERROR tests/test_core.py - ValueError: Unknown mat file type, version 50, 56
ERROR tests/test_io.py - ValueError: Unknown mat file type, version 50, 56
ERROR tests/test_optim.py - ValueError: Unknown mat file type, version 50, 56
ERROR tests/test_redgem.py - ValueError: Unknown mat file type, version 50, 56
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 5 warnings, 5 errors in 5.99s ================================================
(ERROR)-(Exit Code 2)-(Missing keyword, command, or permission problem)
```

I assume the versions of packages now are not compatible with your model/code and if you can hard-code all the packages in requirements.txt it would be really great, otherwise plsease provide a docker image in a registry like dockerhub or quay.io. I can't reproduce the image with your dockerfile. Thanks!
